# Generated by Django 5.2.3 on 2025-06-12 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag_scope_article_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['-is_main', 'tag'], 'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
    ]
