# Generated by Django 5.2.3 on 2025-06-11 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_teachers_remove_student_teacher_alter_student_group_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
