# Generated by Django 5.2.3 on 2025-07-05 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='descriptions',
            new_name='description',
        ),
    ]
