# Generated by Django 5.2.3 on 2025-07-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_rename_descriptions_sensor_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='sensor',
            new_name='sensor_id',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='changed_at',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='created_at',
        ),
        migrations.AddField(
            model_name='measurement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='measurements/'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='temperature',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
